### PR TITLE
Arabic Flavourisation

### PR DESCRIPTION
**Pull request by Charanraja123**
Added Arabic Titles of
Barony
Count
County
Duke
Duchess
Duchy
King
Queen
Kingdom
Emperor (except for bedouin)
Empress (expect for bedouin)
Empire

For the Cultures
Bedouin
Levantine
Egyptian
Maghrebi

Also Moved Maghrebi from chinese to arabic in cultures localisation

Updated the same across all localisations

### CODE REVIEW

**Comment by Gr770** [comment]
This one needs a double pass as the sultan/malik distinction is a religious one not a culture/language one.

Also Coptic Egyptians should use Egyptian Coptic

**Comment by Charanraja123** [comment]
> 
> 
> This one needs a double pass as the sultan/malik distinction is a religious one not a culture/language one.
> 
> Also Coptic Egyptians should use Egyptian Coptic

Alright Okay, I'll take a look at it later and draw up an proper method to sort them out properly and get back to you

**Comment by Gr770** [comment]
Needs a redo with new file names

**Comment by Charanraja123** [comment]
Updated to new file names

**Pull request merged**
