### PR TITLE
Earl/Earldom

### PR DESCRIPTION
**Pull request by Gr770**
Conditional Titles

### CODE REVIEW

**Comment by Gr770** [comment]
Still haven't issues, will work it tomorrow

**Comment by Charanraja123** [comment]
If you want any help, Let me know.

**Comment by Viridianus** [comment]
Just a reminder that we'll probably want to suppress Welsh "Lordships", too. And any similar things.

**Comment by Gr770** [comment]
Must be a scope issue

**Comment by Charanraja123** [comment]
What does your error log say?

**Comment by Gr770** [comment]
Working now... I need to wait for priority fix though.

**Review by Charanraja123 — APPROVED** [review]

**Pull request merged**
