### PR TITLE
Knights - Ready

### PR DESCRIPTION
**Pull request by Gr770**
Long pull request

### CODE REVIEW

**Comment by Charanraja123** [comment]
I do have a more compatible version for Knights, again avoiding vanilla files (except the localization file). Similar to our Council positions, Tell me if that is something you guys are interested in. or Maybe you feel like its an overkill.

**Comment by Viridianus** [comment]
Please do present it!

**Comment by Charanraja123** [comment]
Uhh.. Give me a day's time. I have write up some stuff

**Comment by Viridianus** [comment]
A day's time is _arguably_ over :D

**Comment by Charanraja123** [comment]
Well only arguably, I didn't mean earth days anywhere.

**Comment by Charanraja123** [comment]
Work in progress. Do not commit

**Comment by Charanraja123** [comment]
Ok Its tested and working. You guys can edit if you want.

Do not try to combine between those six other than what I've done. I tried my best to avoid recursion as much as possible, since that usually crashes stuff. 
If anything else, ping me in discord

**Comment by Viridianus** [comment]
So... is it merge-ready now?

**Comment by Charanraja123** [comment]
No no. Still have to add cultures. I've only done few cultural groups

**Comment by Viridianus** [comment]
I _think_ it is ready.

**Comment by Viridianus** [comment]
Gesiþ(as) will be have to put for Anglo-Saxon instead of þegen/þegnas but that could be done in fixes, too.

**Comment by Charanraja123** [comment]
There was a single typo in cornish, Fixed that
Other than that everything seems to be fine.
I think this is merge ready

**Review by Charanraja123 — APPROVED** [review]

**Comment by Viridianus** [comment]
Erm, @Gr770 - could you explain your commit? I made it "South Slavic, but neither Vlach nor Bulgarian". You changed it to "South Slavic, but neither Croatian nor Serbian nor Bulgarian". It doesn't quite make sense.

**Pull request merged**
