### PR TITLE
Russian localization

### PR DESCRIPTION
**Pull request by Viridianus**

### CODE REVIEW

**Comment by Charanraja123** [comment]
@Gr770  How is this a duplicate? Did we already do a Russian Language localization?

**Comment by Gr770** [comment]
I thought this was the Russian titles. My bad.

**Comment by Gr770** [comment]
Is this done?

**Comment by Viridianus** [comment]
Long ago (I merely merged in an earlier version of Master-Fix, that's why you see the plethora of commits).

**Comment by Viridianus** [comment]
@Gr770: I've even checked it for conflicts, only general respect for our rules stops me from merging this myself. Please make a decision on this pull request before you go through any other ones.

**Comment by Charanraja123** [comment]
@Gr770  I second his views. Its been sitting here long for no purpose.

**Pull request merged**
