### PR TITLE
Independent Duchy and County Ready

### PR DESCRIPTION
**Pull request by Charanraja123**

### CODE REVIEW

**Comment by Charanraja123** [comment]
So, This pull request is custom loc for independent dukes. It solves the independent duke problem while also implementing Grand duchies. It is tested and working. Check it out and let me know

**Comment by Gr770** [comment]
No issues with the test files.

**Comment by Viridianus** [comment]
Just an obvious reminder that this should concern independent counties at some point, too.

**Comment by Charanraja123** [comment]
Finished all Culture in first file

**Pull request merged**
