### PR TITLE
Master Fixes

### PR DESCRIPTION
**Pull request by Gr770**

### CODE REVIEW

**Comment by Viridianus** [comment]
Now localization calls for lines which exist in flavorization (at least for English and Anglo-Saxon), ain't it beautiful?

**Comment by Charanraja123** [comment]
So I added in all the Frankish Cultures. I've made the Priority to be 2 for Queen mothers, Until we decide how to approach that. Rest should be okay, I'll work and finish localization within the next hour. 
Having a format ready in the same form of the sheets, really sped things up. For both checking and editing.

**Comment by Viridianus** [comment]
You chose to split princes and stuff which were same for Norman and French or Norman and Occitan despite them being in the same culture. Why?

**Comment by Charanraja123** [comment]
Well, It created a weird combination and there were only two of them same which were different combinations. So it was easier for me to create them separately. It also keeps stuff more organized.  
The thing I could have done is to keep all the queen_mother together. Which I'll do.

**Comment by Charanraja123** [comment]
Fixed consort changes for Anglo Saxon only. Rest of them are not cleaned yet, So I did not want to touch them yet.

**Comment by Viridianus** [comment]
Now wait a second. Why are all Old Saxon titles suddenly occitan?

**Comment by Charanraja123** [comment]
> 
> 
> Now wait a second. Why are all Old Saxon titles suddenly occitan?

Did I mess up? I'm sorry.

**Pull request merged**
