### PR TITLE
Master Fix Request

### PR DESCRIPTION
**Pull request by Gr770**

### CODE REVIEW

**Comment by Charanraja123** [comment]
Can you merge already existing fixes labelled branch with this? So that we can close those.

**Comment by Gr770** [comment]
Because, they weren't contributors when they sent the request, they will have to do it unfortunately.

**Comment by palfourti** [comment]
Hopefully I did this right - moved Italian fixes from my Russian branch

**Comment by Charanraja123** [comment]
> 
> 
> Hopefully I did this right - moved Italian fixes from my Russian branch

Everything looks alright to me.

**Pull request merged**
