### PR TITLE
Marches and Palatinates Updated

### PR DESCRIPTION
**Pull request by Gr770**

### CODE REVIEW

**Comment by Charanraja123** [comment]
So I've updated the structure
This is what we are going into use

**Comment by Charanraja123** [comment]
TESTED AND WORKINg. WE FINALLY DID IT GUYS!!!!!!

**Comment by Gr770** [comment]
BTW, characters lose their title upon death.

**Comment by Charanraja123** [comment]
So. Quick thought. I would leave out language localization till this branch is in a ready to merge state. Because localization in the master branch is going to be changing after Master Fixes, and that might cause us to constantly change stuff here.

**Pull request closed without merging**
