### PR TITLE
Spouse Councillor

### PR DESCRIPTION
**Pull request by Viridianus**
In progress but the general logic, I suppose, is already seen.

### CODE REVIEW

**Comment by Charanraja123** [comment]
I do see it. Unfortunately this does not work. Maybe you didn't see what I said before. 

These defaults in the localization file or not what the vanilla games uses, these are just fall backs. The used ones are called from within the Council File to the vanilla localization directly. 
IF this localisation would have worked. You could have just used `Character.GetTitleAsName` here, why even create this whole thing.

In any case, This is what I was thinking first, then I said I was wrong because of the above reasons.

**Comment by Viridianus** [comment]
Erm... We seem to misunderstand each other. "Vanilla localization" does not exist in some vacuum.

**Comment by Charanraja123** [comment]
It directly calls the Vanilla localization keys present in the `culture_titles_l_english`. 
If you haven,t, check the main council Titles folder and you will understand

**Comment by Gr770** [comment]
CHARACTER has to be capitalized.

So either CHARACTER.GetTitleAsName or CHARACTER.Custom(workaround)

**Comment by Charanraja123** [comment]
Yeah sorry, but my point still stands.

**Comment by Viridianus** [comment]
Sorry... You're wrong. It's NOR, not OR. The part after `#Feudal/Default Fallback` calls for the needed things.

**Comment by Charanraja123** [comment]
Okay its NOR. Sorry. Those comments confused me. 
But Still its the default fall backs, It directs itself to the vanilla flavourisation. Look at all the conditions and descriptions above. If only anything doesn't fit into that, does it come to your file. Which is really nothing, since they cover almost everything.

**Comment by Charanraja123** [comment]
If I am still confusing you, Let me know. 
I'll pull up the file and I can explain it it step by step.

**Comment by Viridianus** [comment]
So we have to edit this file just to comment a bunch of first_valid descriptions?

**Comment by Charanraja123** [comment]
For you method, yes. But if are editing the file, I have a better way. As I said in some alt pull request before
Delete every condition in the for name in the Spouse. Just give one localization and link that localization to "[`ROOT.Char.GetTitleAsName]"
I just tested it. and It works

**Comment by Viridianus** [comment]
It does not. Say, you're an Eorl whose wife is Princess of some Empire. Your tooltip will say Princess (or whatever the localized term is) instead of Eorlwif like it should.

**Comment by Charanraja123** [comment]
Wait. Let me upload some screenshots

**Comment by Viridianus** [comment]
Do your screenshots have the described situation though? For a person who's a princess and a duke's wife, normal title would be the equivalent of Princess rather than of Duchess - but the council menu should use the latter.

**Comment by Charanraja123** [comment]
image
No Spouse Screen
image
Irish Duchy
image
Special Case you asked for

**Comment by Charanraja123** [comment]
Is this okay?

**Comment by Viridianus** [comment]
Oh, yeah, that seems to work! I still don't understand why but it does!

**Pull request closed without merging**
