### PR TITLE
Master Fix Request

### PR DESCRIPTION
**Pull request by Gr770**

### CODE REVIEW

**Comment by Charanraja123** [comment]
All localisations files are same except for the file name and the first name right?

**Comment by Viridianus** [comment]
Should be now.

**Comment by Charanraja123** [comment]
I reorganized the Irish culture and added some localization for principalities in too. Can someone review it before merging to make sure I haven't made any mistake/typo like last time.

**Comment by Viridianus** [comment]
Do we really have to duplicate _feudalclan vs. _tribal if they're identical?

**Comment by Charanraja123** [comment]
That was my bad (in a way). Before starting editing i noticed there were entries in chiefdom, so I thought there would be a unique tribal government or else why enter that. Anyways, only after completing everything and while localizing did I notice the it was the same entry as feudal. Since i already did everything and it did not affect anything coding/performance wise, I just let it be.

**Comment by Viridianus** [comment]
Well, that's a general issue I had already raised on forum: maybe we should mark things where default IS identical in the master sheet.

**Comment by Charanraja123** [comment]
Yes. I'll raise this point (and some others I have on mind) as an issue. I would just let the tribal be for now. Other than that, is everything okay?.

**Comment by Viridianus** [comment]
Other than that, yes, I think so (so @Gr770, please merge it!)

**Comment by Gr770** [comment]
Removed principalities. They would just be petty kings (already built in, they all call themselves Ri)

**Pull request merged**
