### PR TITLE
Master Fixes

### PR DESCRIPTION
**Pull request by Gr770**

### CODE REVIEW

**Comment by Viridianus** [comment]
It seems like the previous master-fixes had not been updated for all langs; changed it now.

**Comment by Charanraja123** [comment]
Fixed Errors in English Republics and one typo of using culture instead of culture group for Goidelic

As of now, No errors in the error log (When combined with the Council Fixes). So I think from now on Everything should work properly.

**Comment by Viridianus** [comment]
Why can't you press love to commits? I love your latest one, @Charanraja123 :D

**Comment by Charanraja123** [comment]
Thanks Mr.Pdx's Error log xP

**Pull request merged**
