### PR TITLE
Central Germanic Update

### PR DESCRIPTION
**Pull request by Charanraja123**
--
Added Central Germanic Titles of
Baron
Baroness
Barony
Count
Countess
County
Duke
Duchess
Duchy
King
Queen
Kingdom
Prince ruler
Princess ruler
Emperor
Empress
Empire
--
For the Cultures
Saxon
Franconian
Swabian
Bavarian
Frisian
Dutch

Also Moved frisian and dutched from west_germanic to central_germanic in cultures localisation

Updated the same across all localisations

### CODE REVIEW

**Comment by Gr770** [comment]
I'm going to edit this to remove duplicates for optimization.

**Comment by Charanraja123** [comment]
> 
> 
> I'm going to edit this to remove duplicates for optimization.

I can remove them. Give me two mins and ill add an commit

**Comment by Charanraja123** [comment]
Um.. Sorry.. But I couldnt resolve it. Can you help me out?

**Comment by Charanraja123** [comment]
I've Created a new branch from the new version of master as i was not able to salvage this

**Pull request closed without merging**
