### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Charanraja123**
Beep Bop

### CODE REVIEW

**Comment by Charanraja123** [comment]
Fixing localisation files, dont commit anything to that

**Comment by Charanraja123** [comment]
So I've finished stuff for Brythonic English localisation.
@Viridianus Just check it over after Aemr adds stuff. 
Thanks 👍

**Comment by Viridianus** [comment]
Since we're cleaning it up, should we maybe unify Pictish and Cumbrian where they are the same (that is, everywhere except non-independent count(ie)s)?

**Comment by Charanraja123** [comment]
Yeah sure. Sorry, I did not see they were the same.

**Comment by Charanraja123** [comment]
So I've cleaned up everything again from the start till Brythonic, checked government types and priority numbers. Fixed a lot. Also updated everything in the sheet. Only prio outlier in the mod is the Goidelic one.

**Pull request merged**
