### PR TITLE
Marches and Palatinates

### PR DESCRIPTION
**Pull request by Gr770**

### CODE REVIEW

**Comment by Gr770** [comment]
`[CHARACTER.Custom('DukeType')]` Does pull the custom Loc. Editing the vassal contract still doesn't update the titles.

Anglo Saxon has the required innovation at the 1066 start date for testing marches.

**Comment by Charanraja123** [comment]
I'll finish up some existing stuff and then take a look at this. 
When you said it worked, did it show the flavorisation at all?

**Comment by Gr770** [comment]
Duke_default shows only. I believe its an issue with contract flag.

Obviously I could just add a character flag to the feudal contract file, but I rather keep vanilla file changes low.

**Comment by Gr770** [comment]
Nevermind, character flags do not work.

**Comment by Charanraja123** [comment]
Did you get anything at all in your error log?

**Comment by Gr770** [comment]
No errors, just can't see an added character flag in vassal_contracts/feudal.

**Comment by Charanraja123** [comment]
I appreciate your optimism

**Comment by Viridianus** [comment]
At least now I see where the conflict _is_. Or do you mean about this branch in general?)

**Comment by Charanraja123** [comment]
This branch is general.. Its like our "dark past", gonna stay here forever :P

**Comment by Gr770** [comment]
Always hopefull 😭

**Comment by Charanraja123** [comment]
> 
> 
> Always hopeful 😭

WE DID IT BUDDY xD

**Comment by Viridianus** [comment]
I have to note that `this_works_scutage` and `this_works_march` are not equivalent)

**Comment by Charanraja123** [comment]
> 
> 
> I have to note that `this_works_scutage` and `this_works_march` are not equivalent)

I think you might be seeing an outdated version, I updated it

**Pull request closed without merging**
